# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b811c71d8d64730ad92a894f504b3c84"
name = "BudPay Payments"
handle = "budpay-payments"
application_url = "https://e325-2c0f-f5c0-b2a-1bcb-a329-3d48-c4fb-e224.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-2549721b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://e325-2c0f-f5c0-b2a-1bcb-a329-3d48-c4fb-e224.ngrok-free.app/auth/callback",
  "https://e325-2c0f-f5c0-b2a-1bcb-a329-3d48-c4fb-e224.ngrok-free.app/auth/shopify/callback",
  "https://e325-2c0f-f5c0-b2a-1bcb-a329-3d48-c4fb-e224.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
